config/routes.rb
Spokenvote::Application.routes.draw do

  root :to => 'application#index'

  ActiveAdmin.routes(self)

  devise_for :users, path_names: { sign_in: "login", sign_out: "logout" },
                     controllers: { omniauth_callbacks: "omniauth_callbacks", :sessions => 'sessions', :registrations => "registrations", :authentications => "authentications" }

  devise_scope :user do
    post 'authentications', to: 'authentications#create'
  end

  resources :users, only: [:show] do
    resources :proposals, only: [:index]
  end

  resources :proposals do
    member do
      get :is_editable
      get :related_vote_in_tree
      get :related_proposals
    end
  end

  resources :votes, only: [:create]

  resources :hubs, only: [:create, :index, :show] do
    resources :proposals
  end

  get 'currentuser' => 'users#currentuser'

  require 'robots_generator'
  get '/robots.txt' => RobotsGenerator
  get 'sitemap.xml' => 'sitemaps#index', format: 'xml', as: :sitemap

  get 'voter_mailer/vote_notification'

  get '/*page' => 'application#index'
  get ':controller(/:action(/:id))(.:format)' => redirect('/')

end

app/models/position.rb
# == Schema Information
#
# Table name: positions
#
#  id          :integer          not null, primary key
#  statement   :string(255)
#  user_id     :integer
#  parent_id   :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  votes_count :integer          default(0)
#  ancestry    :string(255)
#

class Position < ActiveRecord::Base
  attr_accessible :parent_id, :parent, :statement, :user_id, :user, :votes, :votes_attributes

  # Associations
  belongs_to :user
  belongs_to :parent, :class_name => 'position', :foreign_key => 'parent_id'
  has_many :votes
  has_and_belongs_to_many :hubs
  has_and_belongs_to_many :tags

  accepts_nested_attributes_for :votes, :reject_if => :all_blank

  # Validations
  validates :user_id, :presence => true
  validates :statement, :presence => true

  # Other
  has_ancestry
  
  class << self
    def by_hub
      Hub.by_name.map {|gb| gb.positions if gb.positions }.reject {|gb| gb == []}.flatten
    end
  end

  def votes_in_tree
    Rails.cache.fetch("/position/#{self.root.id}/votes_in_tree/#{updated_at}", :expires_at => 5.minutes) do
      [self.root, self.root.descendants].flatten.map(&:votes_count).sum
    end
  end

  def related_positions
    all_positions_in_tree = [self.root, self.root.descendants].flatten
    all_positions_in_tree.delete(self.clone)
    all_positions_in_tree
  end
end

app/helpers/positions_helper.rb
module PositionsHelper
  def position_title(total_votes, username)
    title_text = (total_votes > 0) ? 'Proposal by ' : 'Improvement by '
    content_tag(:h4, raw('&mdash; ') + title_text + username)
  end
end

app/views/positions/_position_vote.html.haml
.span2.position-person
  = (idx + 1).to_s + ':'
  = vote.user.name || vote.user.email
.span8
  = truncate(vote.comment, :length => 140, :omission => '...more')

-if @no_more
  .hide_the_more_link &nbsp;

app/views/positions/index.html.haml
.span11
  %table#proposalsListing.listing
    %thead
      %tr
        %th.table-title{ :colspan => '6' }
          = link_to 'New Proposal', new_proposal_path, :class => 'pull-right btn'
          Positions
      %tr
        %th Hub
        %th{ :colspan => '2'} Proposal
        %th Votes
        %th Rank
        %th Topic Votes

    %tbody
      - prevGB = ''
      - @proposals.each do |proposal|
        - all_related_proposals_votes_count = [proposal.ancestors, proposal.descendants, proposal].flatten.map(&:votes_count).sort
        %tr
          %td
            %strong= proposal.hubs.first.name if proposal.hubs.first.name != prevGB
          - if user_signed_in?
            %td.proposal_buttons
              = link_to 'Improve', new_proposal_path(:parent_id => proposal), :class => 'btn btn-mini btn-primary'
              %br
              = link_to 'Support', '#', 'data-function' => 'display_comment_form', 'data-proposal_id' => proposal.id, :class => 'btn btn-mini btn-success'
            %td
              = link_to proposal.statement, edit_proposal_path(proposal)
          - else
            %td{ :colspan => '2' }
              = link_to proposal.statement, proposal_path(proposal)
          %td= proposal.votes.count
          %td= all_related_proposals_votes_count.index(proposal.votes_count) + 1
          %td= proposal.votes_in_tree
        - prevGB = proposal.hubs.first.name

- if user_signed_in?
  = render :partial => 'shared/comment'